name: build galeriders

on:
  push:
    branches: [master]
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: layerssss/michaelhost-actions-build@master
        with:
          registry: registry.micy.in
          registry_username: layerssss
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          image_name: galeriders/api
          image_tag: latest
          build_context: api
          michaelhost_webhook_url: https://hooks.swarm.micy.in
          michaelhost_secret: ${{ secrets.MICHAELHOST_SECRET }}
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: layerssss/michaelhost-actions-build@master
        with:
          registry: registry.micy.in
          registry_username: layerssss
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          image_name: galeriders/ui
          image_tag: latest
          build_context: ui
          michaelhost_webhook_url: https://hooks.swarm.micy.in
          michaelhost_secret: ${{ secrets.MICHAELHOST_SECRET }}
